name: RetroMol
channels:
  - conda-forge
  - defaults 
dependencies:
  - python=3.10
  - pip
  - pip:
    - rdkit
    - networkx
    - scikit-learn
    - matplotlib
    - plotly
    - umap-learn
    - requests
    - -e .