name: CI

# Specify which Github events will trigger a CI build
on: push

jobs:
  build-package:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        # Install the package in editable mode with the dev dependencies
        python3 -m pip install .[test]
    - name: Test with PyTest
      run: |
        python3 -m pytest --cov=retromol tests
    - name: Check style with Pylint
      run: |
        python3 -m pylint --reports=y retromol