name: Tests

on:
  push:
    branches: [ main, dev ]

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.10" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install graphviz
          pip install tox
      - name: Check code quality with flake8
        run: tox run -e flake8
      - name: Check package metadata with Pyroma
        run: tox run -e pyroma
      - name: Check static typing with MyPy
        run: tox run -e mypy
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.10" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install tox tox-uv
      - name: Test with pytest and generate coverage file
        run:
          tox run -e py